global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "keypers"
    static_configs:
      - targets:
          - "keyper-0:9100"
          - "keyper-1:9100"
          - "keyper-2:9100"
          - "keyper-3:9100"
  - job_name: "snollator"
    static_configs:
      - targets:
          - "snapshot:9100"
